/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceDataRouteImport } from './routes/_workspace.data'
import { Route as WorkspaceDocumentsIndexRouteImport } from './routes/_workspace.documents.index'
import { Route as WorkspaceDocumentsIdRouteImport } from './routes/_workspace.documents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDataRoute = WorkspaceDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocumentsIndexRoute = WorkspaceDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocumentsIdRoute = WorkspaceDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/data': typeof WorkspaceDataRoute
  '/documents/$id': typeof WorkspaceDocumentsIdRoute
  '/documents/': typeof WorkspaceDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/data': typeof WorkspaceDataRoute
  '/documents/$id': typeof WorkspaceDocumentsIdRoute
  '/documents': typeof WorkspaceDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/data': typeof WorkspaceDataRoute
  '/_workspace/documents/$id': typeof WorkspaceDocumentsIdRoute
  '/_workspace/documents/': typeof WorkspaceDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/dashboard' | '/data' | '/documents/$id' | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/data' | '/documents/$id' | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/dashboard'
    | '/_workspace/data'
    | '/_workspace/documents/$id'
    | '/_workspace/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/data': {
      id: '/_workspace/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof WorkspaceDataRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/documents/': {
      id: '/_workspace/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof WorkspaceDocumentsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/documents/$id': {
      id: '/_workspace/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof WorkspaceDocumentsIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceDataRoute: typeof WorkspaceDataRoute
  WorkspaceDocumentsIdRoute: typeof WorkspaceDocumentsIdRoute
  WorkspaceDocumentsIndexRoute: typeof WorkspaceDocumentsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceDataRoute: WorkspaceDataRoute,
  WorkspaceDocumentsIdRoute: WorkspaceDocumentsIdRoute,
  WorkspaceDocumentsIndexRoute: WorkspaceDocumentsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
